# Generated by Django 5.1.5 on 2025-01-15 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productid',
        ),
    ]
